[tools]
fnox = "latest"
java = "latest"
node = "24"
"npm:@ingka-group-digital/skapa-design-system-mcp" = "0.5.5"
"npm:@playwright/mcp" = "latest"
terraform = "latest"
maven = "latest"
"npm:mcp-remote" = "latest"
