
[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 16
offset = { x = 0, y = 3 }

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[terminal]
osc52 = "CopyPaste"

[window]
decorations = "Full"
dynamic_title = true

[window.dimensions]
columns = 140
lines = 80

[general]
import = [
  "~/.config/alacritty/themes/tokyonight_moon.toml",
  #"~/.config/alacritty/themes/skapa_dark.toml"
]
