format = """
[î‚¶](#33658A)\
[î‚°](bg:#ec773e fg:#33658A)\
$directory\
[î‚°](bg:#debc9c fg:#ec773e)\
$git_branch\
$git_status\
[î‚°](fg:#debc9c bg:#40b1e1)\
$bun\
$golang\
$java\
$nodejs\
$python\
$rust\
[î‚°](fg:#40b1e1 bg:#33658A)\
[î‚° ](fg:#33658A)\
"""

right_format = """
$status\
[î‚²](fg:#33658A)\
$cmd_duration\
[î‚²](fg:#484848 bg:#33658A)\
$terraform\
[î‚²](fg:#5cc27c bg:#484848)\
$time\
[î‚´](#5cc27c)\
"""
command_timeout = 1000

[bun]
symbol = "ğŸ "
style = "bg:#40b1e1"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 500
style = "bg:#33658A"
format = '[ ï”  $duration ]($style)'

[directory]
style = "bg:#ec773e"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[docker_context]
symbol = "ïŒˆ "
style = "bg:#5cc27c"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = "ï˜"
style = "bg:#debc9c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#debc9c"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#40b1e1"
version_format = "v${major}.${minor}"
format = '[ $symbol($version) ]($style)'

[gcloud]
symbol = "ó±‡¶"
style = "bg:#484848"
format = '[ $symbol $project ]($style)'

[java]
symbol = "î‰– "
style = "bg:#40b1e1"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#40b1e1"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#40b1e1"
version_format = "v${major}.${minor}"
format = '[ $symbol($version) ]($style)'

[terraform]
symbol = "ğŸ’ "
style = "bg:#484848"
format = '[$symbol $workspace ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5cc27c"
format = '[$time]($style)'
