format = """
[î‚¶](darkblue)\
[î‚°](fg:darkblue bg:orange)\
$directory\
[î‚°](fg:orange bg:skin)\
$git_branch\
$git_status\
[î‚°](fg:skin bg:skyblue)\
$bun\
$golang\
$java\
$nodejs\
$python\
$rust\
[î‚°](fg:skyblue bg:darkblue)\
[î‚° ](fg:darkblue)\
"""

right_format = """
$status\
[î‚²](fg:darkblue)\
$cmd_duration\
[î‚²](fg:blackish bg:darkblue)\
$terraform\
[î‚²](fg:green bg:blackish)\
$time\
[î‚´](green)\
"""
command_timeout = 1000

palette = "skapa"

[palettes.skapa]
darkblue = "#33658A"
skyblue = "#40B1E1"
orange = "#EC773E"
skin = "#DEBC9C"
blackish = "#484848"
green = "#5CC27C"

[bun]
symbol = "ğŸ "
style = "bg:skyblue"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 500
style = "bg:darkblue"
format = '[ ï”  $duration ]($style)'

[directory]
style = "bg:orange"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[docker_context]
symbol = "ïŒˆ "
style = "bg:green"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = "ï˜"
style = "bg:skin"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:skin"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:skyblue"
version_format = "v${major}.${minor}"
format = '[ $symbol($version) ]($style)'

[gcloud]
symbol = "ó±‡¶"
style = "bg:blackish"
format = '[ $symbol $project ]($style)'

[java]
symbol = "î‰– "
style = "bg:skyblue"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:skyblue"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:skyblue"
version_format = "v${major}.${minor}"
format = '[ $symbol($version) ]($style)'

[terraform]
symbol = "ğŸ’ "
style = "bg:blackish"
format = '[$symbol $workspace ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:green"
format = '[$time]($style)'
